spring.application.name=atten_middle

server.port=8821

# ------------------------------------------------------ DB ------------------------------------------------------------
#spring.jpa.database=POSTGRESQL
spring.jpa.database=MYSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:33060/zkteco_db
spring.datasource.jdbc-url=jdbc:mysql://localhost:33060/zkteco_db
#spring.datasource.url=jdbc:mysql://172.16.0.234:33060/zkteco_db
#spring.datasource.jdbc-url=jdbc:mysql://172.16.0.234:33060/zkteco_db
spring.datasource.username=root
spring.datasource.password=jhn@admin9299

remote.datasource.url=jdbc:mysql://172.16.0.245:3306/ecology10
remote.datasource.jdbc-url=jdbc:mysql://172.16.0.245:3306/ecology10
remote.datasource.username=ecology10
remote.datasource.password=6LSh2l6s6bIXCZZ6ZuQ9sc*1
remote.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.security.secret=atten_middle_secret_key_2026
spring.security.expiration=86400



# 解决 Spring Boot 2.6.x/2.7.x 与 Springfox 3.0.0 的路径匹配兼容性问题
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

swagger.dev.location=127.0.0.1:8821

#### mvn clean package -DactivatedProperties=prod

logging.config=classpath:logback-spring-local.xml

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

atten_desktop.download.path=D:/attenDesktop

## MQ configuration
# RabbitMQ 服务器 IP
spring.rabbitmq.host=127.0.0.1
# 默认端口 5672
spring.rabbitmq.port=5672
# 你刚才创建的用户名和密码
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# 虚拟主机，默认为 /
spring.rabbitmq.virtual-host=/
# 开启消息手动确认（可选，保证高可靠性）
spring.rabbitmq.listener.simple.acknowledge-mode=manual

# 建議配置：如果失敗次數過多，進入死信隊列而非原地重試
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
# 達到最大重試次數後，丟棄消息（不重新入隊）
spring.rabbitmq.listener.simple.retry.initial-interval=1000ms


employee.avater.photo=D:\\Photograph\\Photograph