spring.application.name=atten_middle

server.port=8821

# ------------------------------------------------------ DB ------------------------------------------------------------
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/zkteco_db
spring.datasource.username=ray
spring.datasource.password=8023
spring.jpa.show-sql=true


# 解决 Spring Boot 2.6.x/2.7.x 与 Springfox 3.0.0 的路径匹配兼容性问题
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# setup using log config
logging.config=classpath:logback-spring-local.xml

swagger.dev.location=127.0.0.1:8821

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB